### PR TITLE
Implement async_run

### PR DESCRIPTION
**Pull request by tinco**
# Description
This is an implementation of async_run, as described in https://github.com/rethinkdb/rethinkdb/issues/4630. The actual code in net.rb is rather non-idiomatic Ruby so I had to make some changes to the specific implementation.

I also went ahead and implemented em_run using the new async_run to make sure it passes all tests.

@gabor-boros

### CODE REVIEW

**Comment by tinco** [comment]
@gabor-boros I can't seem to compile rethinkdb:next on MacOS I keep getting these errors even after checking out a whole new repo:

```
➜  rethinkdb git:(update-ruby) make
    [1/436] FETCH protobuf_2.5.0
    [2/436] INSTALL-INCLUDE protobuf_2.5.0
    [3/436] BUILD protobuf_2.5.0
    [4/436] PROTOC build/proto/rdb_protocol/ql2.pb.cc
    [5/436] INSTALL-INCLUDE gtest_1.7.0
    [6/436] CC build/release_clang/obj/rdb_protocol/ql2.pb.o
In file included from build/proto/rdb_protocol/ql2.pb.cc:5:
./build/proto/rdb_protocol/ql2.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
./build/proto/rdb_protocol/ql2.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
./build/proto/rdb_protocol/ql2.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
```

I did `rm -r *; git checkout -f; ./configure --allow-fetch --fetch protoc` and it still didn't compile

**Comment by tinco** [comment]
I figured out a modification to the configure script to make it pass through the protoc test, it seems to be happily compiling now. I'll make a PR for that as well if it succesfully compiles.

**Comment by gabor-boros** [comment]
Thank you @tinco!

**Review by gabor-boros — APPROVED** [review]

**Comment by gabor-boros** [comment]
LGTM 👍 🎉

**Comment by tinco** [comment]
I.. wasn't able to run the tests yet :P

**Pull request merged**
